config/routes.rb
Rails.application.routes.draw do
  # get "splash_screen/index"
  root "splash_screen#index"
  get "splash_screen/menu"
  devise_for :users
  resources :groups do
    resources :entities
  end
  # root "groups#index"
  get '/users', to: 'groups#index'
  get '/users/:id', to: 'groups#index'
  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(_user)
    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :group

  validates :name, :amount, :group, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entities

  validates :name, :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable # , :confirmable
  has_many :groups
  has_many :entities

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end

  def after_sign_in_path_for(_user)
    groups_path
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /entities or /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(entity_params)
    @entity.author = current_user
    @entity.group_id = Group.find_by(id: params[:group_id]).id

    respond_to do |format|
      if @entity.save
        format.html { redirect_to group_path(params[:group_id]), notice: 'New transaction added.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to group_entities_path(params[:group_id]), notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:author_id, :name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /groups or /groups.json
  def index
    @groups = Group.includes(:user).where(user: current_user)
  end

  # GET /groups/1 or /groups/1.json
  def show
    @entities = Entity.where(group: @group).order(created_at: :desc)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'New category added.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def index; end

  def menu; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to groups_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to groups_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to splash_screen_menu_path, notice: 'Account was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  <p>
    <strong>Author:</strong>
    <%= entity.author_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= entity.amount %>
  </p>

</div>

app/views/entities/_form.html.erb
<%= form_with model: entity, url: group_entities_path do |form| %>
  <%= render partial: "/layouts/header", locals: {name: "New Transaction", f: form, b_name: "Save"} %>

  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <p>Refresh page and enter correct values</p>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "Name", class: "form"  %>
  </div>

  <div>
    <%= form.text_field :amount, placeholder: "Amount", class: "form"  %>
  </div>

<% end %>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entities</h1>

<div id="entities">
  <% @entities.each do |entity| %>
    <%= render entity %>
    <p>
      <%= link_to "Show this entity", group_entity_path(params[:group_id], entity) %>
    </p>
  <% end %>
</div>

<%= link_to "New entity", new_group_entity_path %>

app/views/entities/new.html.erb
<%= render "form", entity: @entity %>

<br>

app/views/entities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entity %>

<div>
  <%= link_to "Edit this entity", edit_group_entity_path(params[:group_id], @entity) %> |
  <%= link_to "Back to entities", group_entities_path(params[:group_id]) %>

  <%#= button_to "Destroy this entity", group_entity_path(params[:group_id], @entity), method: :delete %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <%= render partial: "/layouts/header", locals: {name: "New Category", f: form, b_name: "Save"} %>

  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <p>Refresh page and enter correct values</p>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "Name", class: "form"  %>
  </div>

  <div>
    <%= form.text_field :icon, placeholder: "Image url", class: "form"  %>
  </div>

<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="groupCard">
  
  <div class="groupCardL">
    <img src= <%=group.icon%> alt="image">
  </div>

  <div class="groupCardC">
    <div>
      <%= link_to group.name, group %>
    </div>
    <div class="groupCardCDate">
      <%= group.created_at.strftime('%d %b %Y') %>
    </div>
  </div>


  <div class="groupCardR">
    <strong>
      <% total = 0 %>
      <% group.entities.each do |entity| %>
        <% total += entity.amount %>
      <% end %>
      $ <%= total %>
    </strong>
  </div>

</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<%= render partial: "/layouts/header", locals: {name: "Categories"} %>

<p style="color: green"><%= notice %></p>

<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
  <% end %>
</div>

<div class="groupIndexButton">
  <%= link_to "Add a new category", new_group_path, class: "groupIndexButtonL" %>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

<br>

app/views/groups/show.html.erb
<%= render partial: "/layouts/header", locals: {name: "Transactions"} %>

<p style="color: green"><%= notice %></p>

<%= render @group %>

<div id="entities">
  <% @entities.each do |entity| %>
    <div class="entity">
      <div>
        Transaction
        <%= entity.name %> <br>
      </div>
      <div class="entityDate">
        <%= entity.created_at.strftime('%d %b %Y') %> at <%= entity.created_at.strftime('%I:%M%P') %> 
        <hr>
      </div>
    </div>
  <% end %>

  <div class="groupIndexButton">
    <%= link_to "Add a new transaction", new_group_entity_path(params[:id]), class: "groupIndexButtonL" %>
  </div>

   <%#= link_to "Edit this group", edit_group_path(@group) %> 
  <%#= link_to "Back to groups", groups_path %>
  <%#= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/_header.html.erb
<div class="header">

  <div class="headerLeft">
    <%- if controller_name == 'sessions' || controller_name == 'registrations' %>
      <%= link_to image_tag("/assets/back"), root_path, class: "headerBack" %><br />
    <%- elsif controller_name == 'groups' && controller.action_name == 'index' %>
      <%= link_to image_tag("/assets/menu"), splash_screen_menu_path, class: "headerBack" %><br />
    <%- elsif controller_name == 'groups' && controller.action_name == 'show' || controller.action_name == 'menu' %>
      <%= link_to image_tag("/assets/back"), groups_path, class: "headerBack" %><br />
    <%- elsif controller_name == 'groups' && controller.action_name == 'new' %>
      <%= link_to image_tag("/assets/back"), groups_path, class: "headerBack" %><br />
    <%- elsif controller_name == 'entities' && controller.action_name == 'new' %>
      <%= link_to image_tag("/assets/back"), group_path(params[:group_id]), class: "headerBack" %><br />
    <%- elsif controller_name == 'users' && controller.action_name == 'edit' %>
      <%= link_to image_tag("/assets/back"), groups_path, class: "headerBack" %><br />
    <% end %>
  </div>

  <div class="headerCenter">
    <%- if controller_name == 'sessions' || controller_name == 'registrations' || controller_name == 'groups' || controller_name == 'entities'%>
      <%= name %>
    <%- elsif controller.action_name == 'menu' %>
      <%= name %>
    <%- elsif controller_name == 'users' && controller.action_name == 'edit' %>
      <%= name %><br />
    <% end %>
  </div>

  <div class="headerRight">
    <%- if controller_name == 'sessions' || controller_name == 'registrations' %>
      <%= f.submit name, class: "headerButton" %>
    <%- elsif controller_name == 'users' && controller.action_name == 'edit' %>
      <%= f.submit b_name, class: "headerButton" %>
    <%- elsif controller.action_name == 'new' && controller_name = 'groups' %>
      <%= f.submit b_name, class: "headerButton" %>
    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/splash_screen/index.html.erb
<div class="splashscreen">
  <h1 class="splashscreenh1">budget app</h1>

  <div class="splashscreenLink" id="sssignIn">
    <%= link_to "Sign in", new_user_session_path %>
  </div>
  <div class="splashscreenLink">
    <%= link_to "Sign up", new_user_registration_path %>
  </div>
</div>

app/views/splash_screen/menu.html.erb
<%= render partial: "/layouts/header", locals: {name: current_user.name} %>

<div class="menuBody">
  <div class="menuItem">
    <%= link_to "Edit account", edit_user_path(current_user), class: "menuLink" %> <hr>
  </div>
  <div class="menuItem">
    <%= link_to "Categories", groups_path, class: "menuLink" %> <hr>
  </div>
  <div class="menuItem">
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "menuButton" %><br />
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <%= render partial: "/layouts/header", locals: {name: "Edit account", f: form, b_name: "Update"} %>

  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "Name", class: "form"  %>
  </div>

<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<%= render "form", user: @user %>

<br>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %><br />

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>